# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_SwiftMatrixLite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo_SwiftMatrixLite
  pod 'SwiftMatrixLite', :path => "/Users/xuhaobo/Documents/github/SwiftMatrixLite/SwiftMatrixLite"
end
